language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t drbalintsimon/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true drbalintsimon/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-docker-react"
    env: "DockerDockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-336879081023"
    bucket_path: "docker-docker-react" # same as app name
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY